Repository opencb/cellbase, pull requests merged in 2019-10, with the labels that each got.

#431 Add library for test code coverage
  pom.xml
Labels: enhancement

#443 441 consolidate docs
  README.md
Labels: documentation

#456 Accept JSON or YAML configuration file
  cellbase-app/pom.xml
  cellbase-app/src/main/java/org/opencb/cellbase/app/cli/CliOptionsParser.java
  cellbase-app/src/main/java/org/opencb/cellbase/app/cli/CommandExecutor.java
  cellbase-core/pom.xml
  cellbase-core/src/main/java/org/opencb/cellbase/core/config/CellBaseConfiguration.java
  cellbase-core/src/main/java/org/opencb/cellbase/core/loader/CellBaseLoader.java
  cellbase-core/src/main/resources/configuration.json
  cellbase-core/src/main/resources/configuration.yml
  cellbase-core/src/test/java/org/opencb/cellbase/core/CellBaseConfigurationTest.java
  cellbase-lib/src/test/java/org/opencb/cellbase/lib/GenericMongoDBAdaptorTest.java
  cellbase-lib/src/test/java/org/opencb/cellbase/lib/monitor/MonitorTest.java
  cellbase-server/src/main/java/org/opencb/cellbase/server/rest/GenericRestWSServer.java
Labels: task
